test: &default

  # Credentials for REST APIs
  client_id: AY151tUHg4FXs0_BnrHoqJ2R1Ja2BhPC9UqfLfzoYKabEBBnQve_M9RCk-w3-7snxVuOlfgKw6kKl5O1
  client_secret: EPSMEMwfP7SgUZUPLxpUuQ9XvrMHDnd24YafsWQhCZdG5huV4O-mQ5uhB_4HtU8IyYmyBdb5h3HorNq4

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  #app_id: APP-80W284485P519543T
  #username: jb-us-seller_api1.paypal.com
  #password: WX4WTU3S8MY44S7F
  #signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  # sandbox_email_address: nscotthend-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
  client_id: Aae4LPAFXbzqYffN0tB4DXS47LCQOGKIsvcbTjobGGiOOYcOEpLpshI0fNWgY-RXabOATrpIHr4NK5Wu
  client_secret: ELUrTGEBDhLApmTGznd8e0Cat_66IkBFczNdPktdtUvtM0IUOG0hTWLcFJOz9bMlIMfxmmMJ82YxXmQh
